  language: cpp

  group: stable
  os: 
     - linux
  dist: xenial
  addons:
    apt:
      packages:
         - libboost-all-dev
         - build-essential 
         - pkg-config 
         - libssl-dev 
         - libzmq3-dev 
         - libunbound-dev 
         - libminiupnpc-dev 
         - libreadline6-dev 
         - libldns-dev

  before_install: 
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get clean; fi
            - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install make cmake build-essential libboost-all-dev pkg-config libssl-dev libzmq3-dev libunbound-dev libminiupnpc-dev libreadline6-dev libldns-dev; fi
  script:
            make

